### ISSUE TITLE
Fix: Create Page Mobile View UI

### ISSUE THREAD

**Issue by p7uverma** [p7uverma/SnapLine#32]
Fix: Create Page Mobile View UI.
Do some better style for mobile view.

![ui-mobile-fix](https://github.com/p7uverma/SnapLine/assets/112266318/218f7899-df56-4bad-92ba-ca26d854e03b)

**Comment by aishwarya-mali** [comment]
@p7uverma I'd like to work on this issue.

**Comment by p7uverma** [comment]
@aishwarya-mali  assigned you this issue.

**Comment by aishwarya-mali** [comment]
@p7uverma I'll start working on this soon.

**Comment by aishwarya-mali** [comment]
@p7uverma,

I am trying to register and get below error. Also, can you tell me if I need .env file and if yes what variables i need to add just for frontend so I can work on this issue.

<img width="952" alt="image" src="https://github.com/p7uverma/SnapLine/assets/43086476/b495336f-cd24-4e5e-ab59-63cda69b957b">
<img width="941" alt="image" src="https://github.com/p7uverma/SnapLine/assets/43086476/647831e5-df1f-428e-8522-8c45e1cad7ba">

**Comment by p7uverma** [comment]
Add all the fields of .env file like DATABASEURL and NEXTAUTHSECREAT

**Comment by aishwarya-mali** [comment]
@p7uverma Is there a way i can go directly to that page?

**Comment by p7uverma** [comment]
@aishwarya-mali No page is private due to security reasons. user must be logged in .
use example .env
```env
# MongoDB connection URL
DATABASE_URL="mongodb+srv://nfme-admins:t73TjDFHdQTiXZ2h@nfme-prod.hk9it6f.mongodb.net/snapline-dev"

# Cloudinary configuration
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="pvserver"
NEXT_PUBLIC_CLOUDINARY_API_SECRET="qmZ3xMSggZBWsbnnH8e9cayMlec"
NEXT_PUBLIC_CLOUDINARY_API_KEY="115251443181415"

# Public URL of the SnapLine application
NEXT_PUBLIC_URL="http://localhost:3000"

# NextAuth configuration
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-nextauth-secret"

# Google OAuth configuration
GOOGLE_CLIENT_ID="621190539158-gltjuld8dprl0ku38511fuo0t7vg2if2.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"

# GitHub OAuth configuration
GITHUB_ID="813d1b3a99d692651e70"
GITHUB_SECRET="5e6b6e46968f2198eaf1cd599992238ba458b1b9"


```
