### ISSUE TITLE
UI: ADD Trends page lInk in navbar

### ISSUE THREAD

**Issue by p7uverma** [p7uverma/SnapLine#39]
We need to add trends page in navbar so users and access trends feature.

- [ ] Add Trend Link in Desktop sidebar
- [ ] Add Trends Link in Mobile bottom navbar

**Comment by rahmlad-aramide** [comment]
Hi @p7uverma 
Kindly assign this issue to me, I'm interested in taking it up.
Thank you

**Comment by rahmlad-aramide** [comment]
Thank you for assigning it to me @p7uverma , I'll get to it

**Comment by rahmlad-aramide** [comment]
Hi @p7uverma 
While trying to setup my development codebase, I can see that there are some required environmental variables which was currently bearing their respective placeholders as showed in the image below:

![image](https://github.com/p7uverma/SnapLine/assets/67334984/271e28e0-c164-4cf8-b4bb-0a1232c3b601)

So, I wanted to confirm if you'll be the one to produce me that or I should source for it from my end?

**Comment by p7uverma** [comment]
These are the dev environment variables
```env
# MongoDB connection URL
DATABASE_URL="mongodb+srv://nfme-admins:t73TjDFHdQTiXZ2h@nfme-prod.hk9it6f.mongodb.net/snapline-dev"

# Cloudinary configuration
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="pvserver"
NEXT_PUBLIC_CLOUDINARY_API_SECRET="qmZ3xMSggZBWsbnnH8e9cayMlec"
NEXT_PUBLIC_CLOUDINARY_API_KEY="115251443181415"

# Public URL of the SnapLine application
NEXT_PUBLIC_URL="http://localhost:3000"

# NextAuth configuration
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-nextauth-secret"

# Google OAuth configuration
GOOGLE_CLIENT_ID="621190539158-gltjuld8dprl0ku38511fuo0t7vg2if2.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"

# GitHub OAuth configuration
GITHUB_ID="813d1b3a99d692651e70"
GITHUB_SECRET="5e6b6e46968f2198eaf1cd599992238ba458b1b9"
```

**Please use this for this project only. Don't misuse.**

**Comment by rahmlad-aramide** [comment]
Yes sure, meanwhile I wanted to say it's public here, I'll suggest you send it to me through a safe and secure means as anyone can get it from here or what do you suggest?
