### ISSUE TITLE
DOC: Fix copying command error in the README file

### ISSUE THREAD

**Issue by rahmlad-aramide** [p7uverma/SnapLine#40]
I noticed an error in the copying command provided in the README file. The current command is causing issues, and it needs to be corrected for it to work as expected.

### Steps to Reproduce:

- Navigate to the README file.
- Locate 4. Edit.env under Installation.
- Follow the provided instructions to execute the command by copying and pasting it to your terminal for execution.
- Observe the error you will get when trying to use the command.

### Expected behaviour:
The contents in the .env.example file should be copied into your newly created .env file

### Additional information:
Find the below problematic command:

#### 4. Edit .env:

```
cp .env.example > .env
```

**Comment by p7uverma** [comment]
Yep! We got you @rahmlad-aramide assigned you.

**Comment by rahmlad-aramide** [comment]
Awesome, thank you
