### ISSUE TITLE
Feature: Show Registered AIs on Search Page 

### ISSUE THREAD

**Issue by p7uverma** [p7uverma/SnapLine#43]
Feature Required: Add Registered AI show on Search Page.
 

- [ ] Create A Card UI To show registered AI image and name with website link button.
- [ ] Implement that in search Page
- [x] Redesign API for that and complete the task.

**Comment by RISHIKESHk07** [comment]
Hey @p7uverma i  would like to contribute , but i am a novice in TS and prisma , would i be able to do it ?

**Comment by p7uverma** [comment]
@RISHIKESHk07 Go up I will help you if you struck on any point 👍

**Comment by p7uverma** [comment]
We did that sorry @RISHIKESHk07
