### ISSUE TITLE
BUG: Error in Random Image in left side of our register and login page.

### ISSUE THREAD

**Issue by p7uverma** [p7uverma/SnapLine#44]
![add-image](https://github.com/p7uverma/SnapLine/assets/112266318/8d8a77d5-881a-49f0-8730-56a31da0f0ba)

- [ ] Add An Random Image in left side of our register and login page.
- [ ] On Page refresh Image should change to random.
**_Remember Image Should be suitable for users._**

**Comment by Rhythm-08** [comment]
Hello, I would like to solve this issue

**Comment by p7uverma** [comment]
@Rhythm-08 We got you! You're in the team let's work together 👏.

**Comment by p7uverma** [comment]
Here we have other task for you @Rhythm-08. 

We have this error in fetching random image.
You can try to solve.
![img-issue](https://github.com/p7uverma/SnapLine/assets/112266318/3ff51597-c9b8-4085-b165-92a2c98d726d)
