### ISSUE TITLE
UI: Username align in start

### ISSUE THREAD

**Issue by p7uverma** [p7uverma/SnapLine#53]
- In profile page username is not aligned at start. it is not look good
- fix that problem..

![bug-username-alignment](https://github.com/p7uverma/SnapLine/assets/112266318/805e342e-460f-487f-a1b8-a49b208703dd)

**Comment by thezeeshann** [comment]
@p7uverma can you assign me this issue?

**Comment by p7uverma** [comment]
@thezeeshann Yep Assigned you! :clap:

**Comment by thezeeshann** [comment]
@p7uverma can you give me any testing user email and password

**Comment by p7uverma** [comment]
@thezeeshann create .env fill important fields you can check from .env.example

```env
# MongoDB connection URL
DATABASE_URL="mongodb+srv://your-username:your-password@your-cluster.mongodb.net/your-database"

# Cloudinary configuration
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="your-cloud-name"
NEXT_PUBLIC_CLOUDINARY_API_SECRET="your-api-secret"
NEXT_PUBLIC_CLOUDINARY_API_KEY="your-api-key"

# Public URL of the SnapLine application
NEXT_PUBLIC_URL="http://localhost:3000"

# NextAuth configuration
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-nextauth-secret"

# Google OAuth configuration
GOOGLE_CLIENT_ID="your-google-client-id"
GOOGLE_CLIENT_SECRET="your-google-client-secret"

# GitHub OAuth configuration
GITHUB_ID="your-github-client-id"
GITHUB_SECRET="your-github-client-secret"

```
create your account and work.

**Comment by thezeeshann** [comment]
@p7uverma  yeah i did

**Comment by thezeeshann** [comment]
@p7uverma When I create an account i get an error 

![Screenshot (268)](https://github.com/p7uverma/SnapLine/assets/88139550/fa774876-fbf9-4e1c-a8d5-edfe9b2f0408)

**Comment by p7uverma** [comment]
@thezeeshann you are using mongodb without replica. Pisma works on mongodb with replicas so please create a db on mongodb atlas to work with or use docker to create a mongodb replica set.

**Comment by aishwarya-mali** [comment]
@p7uverma Is this issue for mobile device?

**Comment by p7uverma** [comment]
@aishwarya-mali issue is of desktop.

**Comment by aishwarya-mali** [comment]
@p7uverma Any specific device? For me it looks good.
<img width="946" alt="image" src="https://github.com/p7uverma/SnapLine/assets/43086476/f0d171ce-6bd7-4fe8-95db-43d2dd6bc040">

**Comment by p7uverma** [comment]
We have updated UI. Please pull new version of code and then check ✔️.
@aishwarya-mali

**Comment by aishwarya-mali** [comment]
Ohh sorry. I see it now. Can I work on this @p7uverma

**Comment by p7uverma** [comment]
@aishwarya-mali Yeh still we are programmers 😂

**Comment by aishwarya-mali** [comment]
@p7uverma Let me know if I can work on it.

**Comment by p7uverma** [comment]
@aishwarya-mali As your wish. I have assigned you!
