### ISSUE TITLE
[BUG] Prompts not showing on profile page

### ISSUE THREAD

**Issue by p7uverma** [p7uverma/SnapLine#54]
When I visit to profile page of any user. There prompts are not showing
![Screenshot_20231008-173229_Chrome.png](https://github.com/p7uverma/SnapLine/assets/112266318/3634e8db-e37f-488c-894d-400ff828ee2c)

**Comment by Sadman95** [comment]
I am getting the response locally from my end.
![image](https://github.com/p7uverma/SnapLine/assets/86881892/8b620408-cdce-4307-84e7-1596f7475de2)

**Comment by p7uverma** [comment]
There was a migration confict in production database. Now it is resloved
